// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0T2C0ZCqJ-GFI_BmfIHX4CmXIOo5x-U',
    appId: '1:218907823867:web:b6d5ed8bd89f607bc96a5e',
    messagingSenderId: '218907823867',
    projectId: 'ichatapp-5d41d',
    authDomain: 'ichatapp-5d41d.firebaseapp.com',
    storageBucket: 'ichatapp-5d41d.appspot.com',
    measurementId: 'G-BTC3NHHENM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6YqmjBpr9qVAHq5a7nSsPJdQGER1JJM',
    appId: '1:218907823867:android:c42dbdc96186c0e6c96a5e',
    messagingSenderId: '218907823867',
    projectId: 'ichatapp-5d41d',
    storageBucket: 'ichatapp-5d41d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Znht3NFukT5I51n9ediJAas3rjAxuPA',
    appId: '1:218907823867:ios:e9ab998673f95c7dc96a5e',
    messagingSenderId: '218907823867',
    projectId: 'ichatapp-5d41d',
    storageBucket: 'ichatapp-5d41d.appspot.com',
    androidClientId: '218907823867-ucq51iijqcl3j0i1a6ki0bdfravmbefo.apps.googleusercontent.com',
    iosClientId: '218907823867-65at6m70b1preed1sl25ddlv5d83fumb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Znht3NFukT5I51n9ediJAas3rjAxuPA',
    appId: '1:218907823867:ios:494f043b6bb54c21c96a5e',
    messagingSenderId: '218907823867',
    projectId: 'ichatapp-5d41d',
    storageBucket: 'ichatapp-5d41d.appspot.com',
    androidClientId: '218907823867-ucq51iijqcl3j0i1a6ki0bdfravmbefo.apps.googleusercontent.com',
    iosClientId: '218907823867-js8j9k5rgb0ebcmcfquhdttkseg3ue3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichat.RunnerTests',
  );
}
